/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.goodhere;

public class AppTest {
  //  @Test public void appHasAGreeting() {
  //    App classUnderTest = new App();
  //
  //  }
}
